name: Publish haakco/deploying-laravel-app-ubuntu-20.04-php8.0-lv Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '30 04 * * 3'

jobs:
  push_to_registry:
    name: Push Docker image haakco/deploying-laravel-app-ubuntu-20.04-php8.0-lv to Docker Hub
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: haakco/deploying-laravel-app-ubuntu-20.04-php8.0-lv
          tags: |
            type=raw,value={{branch}}-{{sha}}
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          build-args:   |
            PHP_VERSION=8.0
            BASE_UBUNTU_VERSION=ubuntu:20.04
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=haakco/deploying-laravel-app-ubuntu-20.04-php8.0-lv:buildcache-deploying-laravel-app-ubuntu-20.04-php8.0-lv
          cache-to: type=registry,ref=haakco/deploying-laravel-app-ubuntu-20.04-php8.0-lv:buildcache-deploying-laravel-app-ubuntu-20.04-php8.0-lv,mode=max
